### ISSUE TITLE
[Feature request] Host only target

### ISSUE THREAD

**Issue by Crzyrndm** [knurling-rs/defmt#716] opened 2022-12-09 21:41 UTC
Several libraries I work with are written with the intention of being shared between host tooling and device firmware. Something that has come up multiple times is that you can't have defmt enabled when building/running tests/examples. This has also struck in the CI setup a few times (`cargo build --all-targets --all-features` fails when not cross compiling).

I see this may have been a thing originally (https://crates.io/crates/defmt-logger) but that doesn't seem to apply now.

## Motivation

* Not needing a device/emulator to check defmt logging messages from calling a function
* Remove duplication: redirecting-to/co-existance with log/tracing would remove the need to duplicate/`cfg!(...)` logging statements depending on the target in many cases
  * currently I often end up with both log and defmt as optional dependencies and a couple of `#[cfg(...)]` statements to make it work (crate level logging modules + extras when formatting compatibility is an issue). 
* `cargo build --all-targets --all-features` could work which helps with having standard CI scripts

**Comment by Urhengulas** [comment] 2022-12-12 17:36
I believe this is a duplicate of https://github.com/knurling-rs/defmt/issues/714. Can you please post a small note about your thoughts there?

**Closed by Urhengulas** 2022-12-12 17:36 UTC
