### ISSUE TITLE
Hardcoded "probe-run" error messages

### ISSUE THREAD

**Issue by Dirbaio** [knurling-rs/defmt#466] opened 2021-05-11 21:06 UTC
`elf2table` prints many error messages telling the user to update `probe-run` etc. `elf2table` is used in tools that are not probe-run, such as `cargo-embed`, which leads to very confused users.

I'm aware `elf2table` is supposed to be only internal to probe-run, but there's real demand for using defmt in other tools. It would be great if this use was officially recognized, stabilizing the API and fixing minor papercuts like these error messages.

**Comment by theunkn0wn1** [comment] 2021-05-11 21:09
Confused user here. +1

**Comment by Urhengulas** [comment] 2021-05-12 22:05
I think this is a duplicate of https://github.com/knurling-rs/defmt/issues/412

**Closed by Urhengulas** 2021-05-12 22:05 UTC
Labels: difficulty: easy, priority: medium, status: needs PR, type: bug
